version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: my-fastapi-container
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always  # Restart the container if it crashes
